### ISSUE TITLE
get_line does not apply correctly for all path segments

### ISSUE THREAD

**Issue by vmario89** [JarrettR/QuickJoint#16]
Hi, since latest pull request, some issues appear if a path has non-linear segments

```
Traceback (most recent call last):
  File "/home/himbeere/.config/inkscape/extensions//quick_joint/quick_joint.py", line 279, in <module>
    QuickJoint().run()
  File "/usr/share/inkscape/extensions/inkex/base.py", line 231, in run
    self.save_raw(self.effect())
  File "/home/himbeere/.config/inkscape/extensions//quick_joint/quick_joint.py", line 263, in effect
    newPath = self.draw_tabs(p, lineNum)
  File "/home/himbeere/.config/inkscape/extensions//quick_joint/quick_joint.py", line 144, in draw_tabs
    cursor, segCount, segment, closePath = self.get_segments(path, line, self.numtabs)
  File "/home/himbeere/.config/inkscape/extensions//quick_joint/quick_joint.py", line 200, in get_segments
    start, end, closePath = QuickJointPath(path).get_line(line)
  File "/home/himbeere/.config/inkscape/extensions/quick_joint/quick_joint.py", line 65, in get_line
    start = complex(self[n].x, self[n].y)
AttributeError: 'Curve' object has no attribute 'x'. Did you mean: 'x2'?
```

![grafik](https://user-images.githubusercontent.com/5631071/198721529-eaca9f17-1ea0-40bd-8ea1-3d7ac2cd2c67.png)

we need some routine to ignore that segment or to convert to regular stupid line

**Comment by vmario89** [comment]
![test](https://user-images.githubusercontent.com/5631071/198736443-692c65e3-8e26-4c69-9974-bc25fa826231.svg)

**Comment by vmario89** [comment]
https://github.com/vmario89/QuickJoint/tree/patch-1 fixes the problem

**Comment by JarrettR** [comment]
Amazing, thank you
